[patch]
title = "洛克人EXE4.5 + PvP补丁 界面汉化"
authors = ["The Rockman EXE Zone", "Greiga Master <griegamaster@gmail.com>"]
source = "https://therockmanexezone.com/pages/exe45-pvp-patch"

[versions.'0.6.0']
netplay_compatibility = "exe45_pvp_preview2_bf3"

[versions.'0.6.0'.rom_overrides]
language = "zh-CN"
charset = [" ", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "*", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "ÿ", "Ÿ", "EX", "SP", "DS", "Œ", "œ", "?", "+", "-", "×", "À", "Á", "Â", "Ã", "Ä", "Å", "Æ", "Ç", "È", "É", "Ê", "Ë", "Ì", "Í", "Î", "Ï", "Ð", "Ñ", "Ò", "Ó", "Ô", "Õ", "Ö", "ý", "Ø", "Ù", "Ú", "Û", "Ü", "Ý", "Þ", "ß", "à", "á", "â", "ã", "ä", "å", "æ", "ç", "è", "é", "ê", "ë", "ì", "í", "î", "ï", "ð", "ñ", "ò", "ó", "ô", "õ", "ö", "þ", "ø", "ù", "ú", "û", "ü", "[×alt]", "÷", "XX", "V2", "V3", "¿", "@", "<", ">", "\\[", "\\]", "[-]", "[×]", "=", ":", "%", "¡", "[+]", "█", "[bat]", "ー", "!", "[V4]", "[V5]", "&", ",", "。", ".", "・", ";", "'", "\"", "~", "/", "(", ")", "「", "」", "α", "β", "Ω", "■", "_", "[z]", "[S]", "[M]", "[G]", "[1px]", "[MB]", "[Trophy1A]", "[Trophy1B]", "[Trophy2A]", "[Trophy2B]", "[TVShow1]", "[TVShow2]", "[Promise1]", "[Promise2]", "[Meal1]", "[Meal2]", "[School1]", "[School2]", "[Other1]", "[Other2]", "[bracket1]", "[bracket2]", "[8px]", "⋯", "$", "€", "£", "¥", "¢", "#", "←", "↑", "→", "↓", "[0lower]", "[1lower]", "[2lower]", "[3lower]", "[4lower]", "[5lower]", "[6lower]", "[7lower]", "[8lower]", "[9lower]", "[Alower]", "[Plower]", "[Mlower]", "[:lower]", "わ", "研", "げ", "ぐ", "ご", "が", "ぎ", "ぜ", "ず", "じ", "ぞ", "ざ", "で", "ど", "づ", "だ", "ぢ", "べ", "ば", "び", "ぼ", "ぶ", "ぽ", "ぷ", "ぴ", "ぺ", "ぱ", "ぅ", "ぁ", "ぃ", "ぉ", "ぇ", "ゅ", "ょ", "っ", "ゃ", "[Ω]", "[←]", "[↓]", "木", "[MB2]", "無", "現", "実", "[circle]", "[cross]", "[#]", "[⋯]", "不", "止", "彩", "[\\[]", "父", "集", "院", "一", "二", "三", "四", "五", "六", "七", "八", "陽", "十", "百", "千", "万", "脳", "上", "下", "左", "右", "手", "足", "日", "目", "月", "[\\]]", "[<]", "人", "入", "出", "山", "口", "光", "電", "気", "助", "科", "次", "名", "前", "学", "校", "省", "祐", "室", "世", "界", "燃", "朗", "枚", "島", "悪", "路", "闇", "大", "小", "中", "自", "分", "間", "系", "花", "問", "[>]", "[$]", "城", "王", "兄", "化", "行", "街", "屋", "水", "見", "終", "丁", "桜", "先", "生", "長", "今", "了", "点", "井", "子", "言", "太", "属", "風", "会", "性", "持", "時", "勝", "赤", "年", "火", "改", "計", "画", "体", "波", "回", "外", "地", "正", "造", "値", "合", "戦", "川", "秋", "原", "町", "所", "用", "金", "郎", "作", "数", "方", "社", "攻", "撃", "力", "同", "武", "何", "発", "少", "以", "白", "早", "暮", "面", "組", "後", "文", "字", "本", "階", "明", "才", "者", "立", "々", "ヶ", "連", "射", "綾", "切", "土", "炎", "伊"]
chips = [
    { name = "" },
    { name = "加农炮" },
    { name = "高超加农炮" },
    { name = "MEGA加农炮" },
    { name = "空气弹" },
    { name = "暴风雪" },
    { name = "灼热吐息" },
    { name = "沉默" },
    { name = "龙卷风" },
    { name = "广域射击1" },
    { name = "广域射击2" },
    { name = "广域射击3" },
    { name = "烈焰线1" },
    { name = "烈焰线2" },
    { name = "烈焰线3" },
    { name = "火神炮1" },
    { name = "火神炮2" },
    { name = "火神炮3" },
    { name = "散射枪" },
    { name = "热焰散弹" },
    { name = "热焰V字" },
    { name = "热焰侧击" },
    { name = "泡沫散弹" },
    { name = "泡沫V字" },
    { name = "泡沫侧击" },
    { name = "烈焰元素" },
    { name = "冰元素" },
    { name = "噪音风暴" },
    { name = "生命同步化" },
    { name = "迷你炸弹" },
    { name = "能量炸弹" },
    { name = "MEGA能量炸弹" },
    { name = "太阳铳1" },
    { name = "太阳铳2" },
    { name = "太阳铳3" },
    { name = "磁螺丝1" },
    { name = "磁螺丝2" },
    { name = "磁螺丝3" },
    { name = "弹跳音符1" },
    { name = "弹跳音符2" },
    { name = "弹跳音符3" },
    { name = "BUG炸弹" },
    { name = "电击" },
    { name = "木之粉末" },
    { name = "炮丸" },
    { name = "间歇泉" },
    { name = "黑色炸弹" },
    { name = "沙之圆环" },
    { name = "剑" },
    { name = "宽剑" },
    { name = "长剑" },
    { name = "宽刃" },
    { name = "长刃" },
    { name = "风神球拍" },
    { name = "改装剑" },
    { name = "变化剑" },
    { name = "居合架式" },
    { name = "雷电球1" },
    { name = "雷电球2" },
    { name = "雷电球3" },
    { name = "反击" },
    { name = "子弹强化" },
    { name = "升级" },
    { name = "气垫球1" },
    { name = "气垫球2" },
    { name = "气垫球3" },
    { name = "旋转枪1" },
    { name = "旋转枪2" },
    { name = "旋转枪3" },
    { name = "双生獠牙1" },
    { name = "双生獠牙2" },
    { name = "双生獠牙3" },
    { name = "纯白之网1" },
    { name = "纯白之网2" },
    { name = "纯白之网3" },
    { name = "回力镖1" },
    { name = "回力镖2" },
    { name = "回力镖3" },
    { name = "天降竹刺1" },
    { name = "天降竹刺2" },
    { name = "天降竹刺3" },
    { name = "竹枪" },
    { name = "钻椎臂" },
    { name = "突风" },
    { name = "抽风机" },
    { name = "炸弹小子1" },
    { name = "炸弹小子2" },
    { name = "炸弹小子3" },
    { name = "钢盔防御1" },
    { name = "钢盔防御2" },
    { name = "钢盔防御3" },
    { name = "裂缝射击" },
    { name = "双重射击" },
    { name = "三重射击" },
    { name = "大型枪弹" },
    { name = "偷窃凝胶" },
    { name = "招来蛇" },
    { name = "定时炸弹" },
    { name = "隐形地雷" },
    { name = "石头方块" },
    { name = "加油歌" },
    { name = "噪音" },
    { name = "定音鼓" },
    { name = "稻草人" },
    { name = "大槌1" },
    { name = "大槌2" },
    { name = "大槌3" },
    { name = "回复10" },
    { name = "回复30" },
    { name = "回复50" },
    { name = "回复80" },
    { name = "回复120" },
    { name = "回复150" },
    { name = "回复200" },
    { name = "回复300" },
    { name = "修复" },
    { name = "地面窃取" },
    { name = "区域窃取" },
    { name = "偷窃复仇" },
    { name = "偷窃惩罚" },
    { name = "缓慢量表" },
    { name = "快速量表" },
    { name = "地面复原" },
    { name = "死斗1" },
    { name = "死斗2" },
    { name = "死斗3" },
    { name = "叶元素" },
    { name = "色点" },
    { name = "砂元素" },
    { name = "盲目" },
    { name = "绒绒圆冲刺1" },
    { name = "绒绒圆冲刺2" },
    { name = "绒绒圆冲刺3" },
    { name = "隐身" },
    { name = "地底下" },
    { name = "防护罩" },
    { name = "防护罩100" },
    { name = "防护罩200" },
    { name = "超级北风" },
    { name = "神圣地面" },
    { name = "岩浆种子" },
    { name = "冰之种子" },
    { name = "草地种子" },
    { name = "元素陷阱" },
    { name = "领航员征用" },
    { name = "替身" },
    { name = "空手夺白刃" },
    { name = "劣质药品" },
    { name = "复制损伤" },
    { name = "攻击+10" },
    { name = "领航员+20" },
    { name = "萝露之箭1" },
    { name = "萝露之箭2" },
    { name = "萝露之箭3" },
    { name = "气力拳1" },
    { name = "气力拳2" },
    { name = "气力拳3" },
    { name = "螺旋桨炸弹1" },
    { name = "螺旋桨炸弹2" },
    { name = "螺旋桨炸弹3" },
    { name = "搜索炸弹1" },
    { name = "搜索炸弹2" },
    { name = "搜索炸弹3" },
    { name = "流星雨1" },
    { name = "流星雨2" },
    { name = "流星雨3" },
    { name = "雷电1" },
    { name = "雷电2" },
    { name = "雷电3" },
    { name = "隼斩1" },
    { name = "隼斩2" },
    { name = "隼斩3" },
    { name = "数字球1" },
    { name = "数字球2" },
    { name = "数字球3" },
    { name = "钢铁齿轮1" },
    { name = "钢铁齿轮2" },
    { name = "钢铁齿轮3" },
    { name = "地面射击1" },
    { name = "地面射击2" },
    { name = "地面射击3" },
    { name = "水柱喷发1" },
    { name = "水柱喷发2" },
    { name = "水柱喷发3" },
    { name = "绿林1" },
    { name = "绿林2" },
    { name = "绿林3" },
    { name = "黑暗加农炮" },
    { name = "黑暗剑" },
    { name = "黑暗炸弹" },
    { name = "黑暗火神炮" },
    { name = "黑暗枪" },
    { name = "黑暗散射" },
    { name = "黑暗战场" },
    { name = "黑暗回复" },
    { name = "空气轮1" },
    { name = "空气轮2" },
    { name = "空气轮3" },
    { name = "沙虫" },
    { name = "预备5" },
    { name = "预备6" },
    { name = "梦之灵" },
    { name = "妖刀村正" },
    { name = "地藏像" },
    { name = "毒气阿努比斯" },
    { name = "攻击+30" },
    { name = "BUG修正" },
    { name = "双重点数" },
    { name = "圣殿" },
    { name = "量表全满" },
    { name = "流星群" },
    { name = "BUG链" },
    { name = "嫉妒" },
    { name = "黑暗元素" },
    { name = "黑色尾翼" },
    { name = "神之锤" },
    { name = "正义的一击" },
    { name = "NEO变化" },
    { name = "Z光剑" },
    { name = "太阳铳EX" },
    { name = "超级火神炮" },
    { name = "萝露" },
    { name = "萝露SP" },
    { name = "萝露EX" },
    { name = "气力人" },
    { name = "气力人SP" },
    { name = "气力人EX" },
    { name = "风人" },
    { name = "风人SP" },
    { name = "风人EX" },
    { name = "侦察人" },
    { name = "侦察人SP" },
    { name = "侦察人EX" },
    { name = "火焰人" },
    { name = "火焰人SP" },
    { name = "火焰人EX" },
    { name = "闪电人" },
    { name = "闪电人SP" },
    { name = "闪电人EX" },
    { name = "布鲁斯" },
    { name = "布鲁斯SP" },
    { name = "布鲁斯EX" },
    { name = "数字人" },
    { name = "数字人SP" },
    { name = "数字人EX" },
    { name = "金属人" },
    { name = "金属人SP" },
    { name = "金属人EX" },
    { name = "废铁人" },
    { name = "废铁人SP" },
    { name = "废铁人EX" },
    { name = "水人" },
    { name = "水人SP" },
    { name = "水人EX" },
    { name = "木头人" },
    { name = "木头人SP" },
    { name = "木头人EX" },
    { name = "陀螺人" },
    { name = "陀螺人SP" },
    { name = "陀螺人EX" },
    { name = "阴暗人" },
    { name = "阴暗人SP" },
    { name = "阴暗人EX" },
    { name = "火枪人" },
    { name = "火枪人SP" },
    { name = "火枪人EX" },
    { name = "寒冷人" },
    { name = "寒冷人SP" },
    { name = "寒冷人EX" },
    { name = "火花人" },
    { name = "火花人SP" },
    { name = "火花人EX" },
    { name = "雷射人" },
    { name = "雷射人SP" },
    { name = "雷射人EX" },
    { name = "剑道人" },
    { name = "剑道人SP" },
    { name = "剑道人EX" },
    { name = "影像人" },
    { name = "影像人SP" },
    { name = "影像人EX" },
    { name = "标记" },
    { name = "加农炮模式" },
    { name = "炮丸模式" },
    { name = "剑模式" },
    { name = "火焰加成" },
    { name = "雷电加成" },
    { name = "水之力" },
    { name = "木之力" },
    { name = "黑色武器" },
    { name = "最后一枪" },
    { name = "未定" },
    { name = "未定" },
    { name = "未定" },
    { name = "未定" },
    { name = "未定" },
    { name = "未定" },
    { name = "未定" },
    { name = "未定" },
    { name = "未定" },
    { name = "未定" },
    { name = "佛鲁迪" },
    { name = "三角刀锋" },
    { name = "诅咒BUG" },
    { name = "流星红日" },
    { name = "红色信号" },
    { name = "佛鲁迪另" },
    { name = "神圣梦幻" },
    { name = "黑色防护罩" },
    { name = "蓝月射线" },
    { name = "BUG集气" },
    { name = "迪欧" },
    { name = "胜者之力" },
    { name = "未定" },
    { name = "未定" },
    { name = "未定" },
    { name = "未定" },
    { name = "未定" },
    { name = "未定" },
    { name = "未定" },
    { name = "黑暗救世主NEO" },
    { name = "热焰散射" },
    { name = "泡沫散射" },
    { name = "GIGA加农炮1" },
    { name = "GIGA加农炮2" },
    { name = "GIGA加农炮3" },
    { name = "超级广域1" },
    { name = "超级广域2" },
    { name = "超级广域3" },
    { name = "烈焰交错1" },
    { name = "烈焰交错2" },
    { name = "烈焰交错3" },
    { name = "地狱回力镖1" },
    { name = "地狱回力镖2" },
    { name = "地狱回力镖3" },
    { name = "疯狂獠牙1" },
    { name = "疯狂獠牙2" },
    { name = "疯狂獠牙3" },
    { name = "地狱气垫球1" },
    { name = "地狱气垫球2" },
    { name = "地狱气垫球3" },
    { name = "磁力冲击1" },
    { name = "磁力冲击2" },
    { name = "磁力冲击3" },
    { name = "梦之剑" },
    { name = "吸血鬼净化系统" },
    { name = "GIGA定时炸弹" },
    { name = "毒气法老王" },
    { name = "贴身护卫" },
    { name = "超级爆破" },
    { name = "未定" },
    { name = "未定" },
    { name = "洛克之魂" },
    { name = "萝露之魂" },
    { name = "气力之魂" },
    { name = "风之魂" },
    { name = "侦察之魂" },
    { name = "火焰之魂" },
    { name = "闪电之魂" },
    { name = "布鲁斯之魂" },
    { name = "数字之魂" },
    { name = "金属之魂" },
    { name = "废铁之魂" },
    { name = "水之魂" },
    { name = "木之魂" },
    { name = "迪欧之魂" },
    { name = "佛鲁迪之魂" },
    { name = "黑暗之魂" },
    { name = "黑暗雷射" },
    { name = "????" },
    { name = "斗士剑" },
    { name = "音速爆击" },
    { name = "诅咒" },
    { name = "神罚" },
    { name = "十字剑" },
    { name = "超级音速" },
    { name = "双重梦幻" },
    { name = "快转" },
    { name = "倒带" },
    { name = "对招练习" },
    { name = "齿轮转换" },
    { name = "骚灵" },
    { name = "冰块" },
    { name = "莱西支援" },
    { name = "比特支援" },
    { name = "探戈支援" },
    { name = "最后一枪" },
    { name = "气力机关枪" },
    { name = " " },
    { name = "迪欧" },
    { name = "胜者之力" },
]
