[patch]
title = "洛克人EXE1 界面汉化"
authors = ["Capcom"]

[versions.'1.0.0']
netplay_compatibility = "exe1_interface"

[versions.'1.0.0'.rom_overrides]
language = "zh-CN"
chips = [
    { name = "  " },
    { name = "加农炮" },
    { name = "高超加农炮" },
    { name = "MEGA加农炮" },
    { name = "剑" },
    { name = "宽剑" },
    { name = "长剑" },
    { name = "小型炸弹" },
    { name = "十字炸弹" },
    { name = "大型炸弹" },
    { name = "散射枪" },
    { name = "泡沫散射" },
    { name = "热焰散射" },
    { name = "迷你炸弹" },
    { name = "散弹枪" },
    { name = "十字枪" },
    { name = "冲击波" },
    { name = "音速波" },
    { name = "动能波" },
    { name = "烈焰塔" },
    { name = "水柱塔" },
    { name = "木桩塔" },
    { name = "地震动1" },
    { name = "地震动2" },
    { name = "地震动3" },
    { name = "烈焰剑" },
    { name = "电力剑" },
    { name = "水斩剑" },
    { name = "气力拳" },
    { name = "寒冰拳" },
    { name = "斗士剑" },
    { name = "冲刺攻击" },
    { name = "骑士剑" },
    { name = "英雄剑" },
    { name = "钢盔防御" },
    { name = "XX" },
    { name = "XX" },
    { name = "三重箭" },
    { name = "三重矛" },
    { name = "三重枪" },
    { name = "台风" },
    { name = "飓风" },
    { name = "旋风" },
    { name = "炮丸" },
    { name = "雷电球1" },
    { name = "雷电球2" },
    { name = "雷电球3" },
    { name = "XX" },
    { name = "XX" },
    { name = "蛋蛇1" },
    { name = "蛋蛇2" },
    { name = "蛋蛇3" },
    { name = "破碎锤" },
    { name = "XX" },
    { name = "XX" },
    { name = "烈焰冲击" },
    { name = "XX" },
    { name = "XX" },
    { name = "巨鼠1" },
    { name = "巨鼠2" },
    { name = "巨鼠3" },
    { name = "锁定1" },
    { name = "锁定2" },
    { name = "锁定3" },
    { name = "击碎地面1" },
    { name = "击碎地面3" },
    { name = "XX" },
    { name = "回复10" },
    { name = "回复30" },
    { name = "回复50" },
    { name = "回复80" },
    { name = "回复120" },
    { name = "回复150" },
    { name = "回复200" },
    { name = "回复300" },
    { name = "XX" },
    { name = "区域窃取" },
    { name = "XX" },
    { name = "XX" },
    { name = "死斗1" },
    { name = "死斗2" },
    { name = "XX" },
    { name = "逃脱" },
    { name = "干扰" },
    { name = "梦之灵" },
    { name = "水之灵" },
    { name = "焰之灵" },
    { name = "木之灵" },
    { name = "地面复原" },
    { name = "XX" },
    { name = "XX" },
    { name = "云" },
    { name = "多云" },
    { name = "密云" },
    { name = "冰方块" },
    { name = "石头方块" },
    { name = "XX" },
    { name = "定时炸弹1" },
    { name = "定时炸弹2" },
    { name = "定时炸弹3" },
    { name = "隐身1" },
    { name = "隐身2" },
    { name = "隐身3" },
    { name = "钢铁躯体" },
    { name = "XX" },
    { name = "遥控雷鼓1" },
    { name = "遥控雷鼓2" },
    { name = "遥控雷鼓3" },
    { name = "子弹防御" },
    { name = "子弹炸弹" },
    { name = "子弹剑" },
    { name = "子弹拳" },
    { name = "电环1" },
    { name = "电环2" },
    { name = "电环3" },
    { name = "远距蜡烛1" },
    { name = "远距蜡烛2" },
    { name = "远距蜡烛3" },
    { name = "慢速量表" },
    { name = "快速量表" },
    { name = "XX" },
    { name = "蚊子1" },
    { name = "蚊子2" },
    { name = "蚊子3" },
    { name = "隐形地雷1" },
    { name = "隐形地雷2" },
    { name = "隐形地雷3" },
    { name = "盖亚槌1" },
    { name = "盖亚槌2" },
    { name = "盖亚槌3" },
    { name = "泡沫包覆1" },
    { name = "泡沫包覆2" },
    { name = "泡沫包覆3" },
    { name = "海啸" },
    { name = "红海啸" },
    { name = "巨海啸" },
    { name = "村正" },
    { name = "阁楼" },
    { name = "地底下" },
    { name = "炸药1" },
    { name = "炸药2" },
    { name = "炸药3" },
    { name = "毒气阿努比斯" },
    { name = "XX" },
    { name = "XX" },
    { name = "钢铁盾" },
    { name = "飞叶盾" },
    { name = "防护罩" },
    { name = "法老王人" },
    { name = "法老王人V2" },
    { name = "法老王人V3" },
    { name = "阴影人" },
    { name = "阴影人V2" },
    { name = "阴影人V3" },
    { name = "XX" },
    { name = "XX" },
    { name = "XX" },
    { name = "魔术人" },
    { name = "魔术人V2" },
    { name = "魔术人V3" },
    { name = "萝露" },
    { name = "萝露V2" },
    { name = "萝露V3" },
    { name = "气力人" },
    { name = "气力人V2" },
    { name = "气力人V3" },
    { name = "布鲁斯" },
    { name = "布鲁斯V2" },
    { name = "布鲁斯V3" },
    { name = "木头人" },
    { name = "木头人V2" },
    { name = "木头人V3" },
    { name = "火焰人" },
    { name = "火焰人V2" },
    { name = "火焰人V3" },
    { name = "数字人" },
    { name = "数字人V2" },
    { name = "数字人V3" },
    { name = "石头人" },
    { name = "石头人V2" },
    { name = "石头人V3" },
    { name = "冰冻人" },
    { name = "冰冻人V2" },
    { name = "冰冻人V3" },
    { name = "骷髅人" },
    { name = "骷髅人V2" },
    { name = "骷髅人V3" },
    { name = "色彩人" },
    { name = "色彩人V2" },
    { name = "色彩人V3" },
    { name = "炸弹人" },
    { name = "炸弹人V2" },
    { name = "炸弹人V3" },
    { name = "鲨鱼人" },
    { name = "鲨鱼人V2" },
    { name = "鲨鱼人V3" },
    { name = "电力人" },
    { name = "电力人V2" },
    { name = "电力人V3" },
    { name = "佛鲁迪" },
    { name = "XX" },
    { name = "XX" },
    { name = "赛塔加农炮1" },
    { name = "赛塔加农炮2" },
    { name = "赛塔加农炮3" },
    { name = "赛塔散射" },
    { name = "赛塔巨鼠1" },
    { name = "赛塔巨鼠2" },
    { name = "赛塔巨鼠3" },
    { name = "赛塔箭" },
    { name = "赛塔矛" },
    { name = "赛塔枪" },
    { name = "奥米加加农炮1" },
    { name = "奥米加加农炮2" },
    { name = "奥米加加农炮3" },
    { name = "奥米加散射" },
    { name = "奥米加巨鼠1" },
    { name = "奥米加巨鼠2" },
    { name = "奥米加巨鼠3" },
    { name = "奥米加箭" },
    { name = "奥米加矛" },
    { name = "奥米加枪" },
    { name = "贝塔炸弹" },
    { name = "贝塔剑" },
    { name = "贝塔波" },
    { name = "贝塔震" },
    { name = "西格玛炸弹" },
    { name = "西格玛剑" },
    { name = "西格玛波" },
    { name = "西格玛震" },
    { name = "强力加农炮" },
    { name = "沉重践踏" },
    { name = "巨大直拳" },
    { name = "血之吸吮" },
    { name = "死亡风暴" },
    { name = "气力射击" },
    { name = "千钧一发" },
    { name = "双人英雄" },
    { name = "XX" },
    { name = "XX" },
    { name = "HP内存" },
    { name = "子弹强化" },
    { name = "法老王陷阱" },
    { name = "XX" },
    { name = "热焰装甲" },
    { name = "水行装甲" },
    { name = "木质装甲" },
    { name = "XX" },
    { name = "XX" },
    { name = "XX" },
    { name = "XX" },
    { name = "XX" },
    { name = "XX" },
    { name = "XX" },
    { name = "XX" },
    { name = "" },
]

