[patch]
title = "洛克人EXE3 黑版BLX 中文化"
authors = ["NW洛克人爱好者&flyeyes汉化组 <593002516@qq.com>"]

[versions.'1.3.0']
netplay_compatibility = "bn3"

[versions.'1.3.1']
netplay_compatibility = "bn3"

[versions.'1.4.0']
netplay_compatibility = "bn3"

[versions.'1.4.0'.rom_overrides]
language = "zh-CN"
chips = [
    { name = "洛克炮" },
    { name = "加农炮" },
    { name = "高级加农" },
    { name = "超级加农" },
    { name = "空气炮1" },
    { name = "空气炮2" },
    { name = "空气炮3" },
    { name = "岩浆炮1" },
    { name = "岩浆炮2" },
    { name = "岩浆炮3" },
    { name = "贯穿炮" },
    { name = "V型炮" },
    { name = "横贯炮" },
    { name = "霰弹炮" },
    { name = "贯穿水泡" },
    { name = "V型水炮" },
    { name = "横贯水泡" },
    { name = "贯穿火焰" },
    { name = "V型火焰" },
    { name = "横贯火焰" },
    { name = "迷你炸弹" },
    { name = "小爆弹" },
    { name = "双爆弹" },
    { name = "三爆弹" },
    { name = "破地钢球" },
    { name = "冻地冰球" },
    { name = "灼地火球" },
    { name = "黑炸弹1" },
    { name = "黑炸弹2" },
    { name = "黑炸弹3" },
    { name = "剑" },
    { name = "阔剑" },
    { name = "长剑" },
    { name = "火焰剑" },
    { name = "碧水剑" },
    { name = "雷击剑" },
    { name = "青竹剑" },
    { name = "自定剑" },
    { name = "变幻剑" },
    { name = "踏前斩" },
    { name = "踏前连斩" },
    { name = "混乱同步" },
    { name = "疾风剑" },
    { name = "居合斩" },
    { name = "冲击波" },
    { name = "音速波" },
    { name = "光束波" },
    { name = "气力拳" },
    { name = "气力冲拳" },
    { name = "气力重拳" },
    { name = "风暴1" },
    { name = "风暴2" },
    { name = "风暴3" },
    { name = "冲刺攻击" },
    { name = "热焰环绕" },
    { name = "火图腾1" },
    { name = "火图腾2" },
    { name = "火图腾3" },
    { name = "老鼠弹1" },
    { name = "老鼠弹2" },
    { name = "老鼠弹3" },
    { name = "海浪波" },
    { name = "灼浪波" },
    { name = "浊浪波" },
    { name = "钢锤" },
    { name = "旋风" },
    { name = "电击环1" },
    { name = "电击环2" },
    { name = "电击环3" },
    { name = "摇摇1" },
    { name = "摇摇2" },
    { name = "摇摇3" },
    { name = "毒孢子1" },
    { name = "毒孢子2" },
    { name = "毒孢子3" },
    { name = "背刺竹" },
    { name = "梦幻虫" },
    { name = "挖地鼠" },
    { name = "缠绕藤1" },
    { name = "缠绕藤2" },
    { name = "缠绕藤3" },
    { name = "密林炮1" },
    { name = "密林炮2" },
    { name = "密林炮3" },
    { name = "回旋镖1" },
    { name = "回旋镖2" },
    { name = "回旋镖3" },
    { name = "追击流星" },
    { name = "撞地流星" },
    { name = "射击流星" },
    { name = "雪花1" },
    { name = "雪花2" },
    { name = "雪花3" },
    { name = "交向电1" },
    { name = "交向电2" },
    { name = "交向电3" },
    { name = "电蜂刺1" },
    { name = "电蜂刺2" },
    { name = "电蜂刺3" },
    { name = "计时弹" },
    { name = "地雷" },
    { name = "死神眼1" },
    { name = "死神眼2" },
    { name = "死神眼3" },
    { name = "诅咒盾1" },
    { name = "诅咒盾2" },
    { name = "诅咒盾3" },
    { name = "间歇泉" },
    { name = "毒面具" },
    { name = "毒鬼脸" },
    { name = "哑铃摆1" },
    { name = "哑铃摆2" },
    { name = "哑铃摆3" },
    { name = "破坏波" },
    { name = "超岩浆炮" },
    { name = "热焰冲刺" },
    { name = "热焰侧绕" },
    { name = "火焰鼠弹" },
    { name = "反射盾" },
    { name = "破地一格" },
    { name = "破地一排" },
    { name = "回复10" },
    { name = "回复30" },
    { name = "回复50" },
    { name = "回复80" },
    { name = "回复120" },
    { name = "回复150" },
    { name = "回复200" },
    { name = "回复300" },
    { name = "占地一格" },
    { name = "占地一排" },
    { name = "家门蛇" },
    { name = "支援1" },
    { name = "水灵灵1" },
    { name = "水灵灵2" },
    { name = "水灵灵3" },
    { name = "偷地惩罚" },
    { name = "偷地复仇" },
    { name = "全场裂地" },
    { name = "全场破地" },
    { name = "全场毒地" },
    { name = "石块" },
    { name = "棱镜" },
    { name = "吹风机" },
    { name = "吸风机" },
    { name = "地震波1" },
    { name = "地震波2" },
    { name = "地震波3" },
    { name = "NO光束1" },
    { name = "NO光束2" },
    { name = "NO光束3" },
    { name = "棋子卒" },
    { name = "棋子马" },
    { name = "棋子车" },
    { name = "尖刺虫1" },
    { name = "尖刺虫2" },
    { name = "尖刺虫3" },
    { name = "慢槽" },
    { name = "快槽" },
    { name = "地台修复" },
    { name = "隐身" },
    { name = "黑洞" },
    { name = "掩护1" },
    { name = "掩护2" },
    { name = "掩护3" },
    { name = "剑之影" },
    { name = "安全帽" },
    { name = "电击兔" },
    { name = "空气鞋" },
    { name = "支援2" },
    { name = "冲锋号" },
    { name = "不协号" },
    { name = "定音号" },
    { name = "防护罩" },
    { name = "护罩100" },
    { name = "护罩200" },
    { name = "防护环" },
    { name = "极地风" },
    { name = "圣地一格" },
    { name = "岩浆地台" },
    { name = "冰冻地台" },
    { name = "绿草地台" },
    { name = "沙漠地台" },
    { name = "金属地台" },
    { name = "圣域" },
    { name = "剑骑士" },
    { name = "火焰狼" },
    { name = "毒蘑菇" },
    { name = "水浪母" },
    { name = "杀人眼" },
    { name = "替身术" },
    { name = "空手夺刃" },
    { name = "机兵反叛" },
    { name = "回复反扣" },
    { name = "伤害复制" },
    { name = "攻击+10" },
    { name = "火攻+30" },
    { name = "水攻+30" },
    { name = "电攻+30" },
    { name = "木攻+30" },
    { name = "机兵+20" },
    { name = "生命环" },
    { name = "村正刀" },
    { name = "地藏王" },
    { name = "阿努比斯" },
    { name = "攻击+30" },
    { name = "机兵+40" },
    { name = "英雄剑" },
    { name = "宙斯之锤" },
    { name = "上帝之石" },
    { name = "千年古木" },
    { name = "满槽" },
    { name = "流星雨" },
    { name = "神来之力" },
    { name = "嫉妒" },
    { name = "烈焰投射" },
    { name = "水流喷射" },
    { name = "电光闪" },
    { name = "盖亚剑" },
    { name = "萝露" },
    { name = "萝露V2" },
    { name = "萝露V3" },
    { name = "气力人" },
    { name = "气力人V2" },
    { name = "气力人V3" },
    { name = "气力人V4" },
    { name = "气力人V5" },
    { name = "布鲁斯" },
    { name = "布鲁斯V2" },
    { name = "布鲁斯V3" },
    { name = "布鲁斯V4" },
    { name = "布鲁斯V5" },
    { name = "闪光人" },
    { name = "闪光人V2" },
    { name = "闪光人V3" },
    { name = "闪光人V4" },
    { name = "闪光人V5" },
    { name = "野兽人" },
    { name = "野兽人V2" },
    { name = "野兽人V3" },
    { name = "野兽人V4" },
    { name = "野兽人V5" },
    { name = "泡泡人" },
    { name = "泡泡人V2" },
    { name = "泡泡人V3" },
    { name = "泡泡人V4" },
    { name = "泡泡人V5" },
    { name = "沙漠人" },
    { name = "沙漠人V2" },
    { name = "沙漠人V3" },
    { name = "沙漠人V4" },
    { name = "沙漠人V5" },
    { name = "旋花人" },
    { name = "旋花人V2" },
    { name = "旋花人V3" },
    { name = "旋花人V4" },
    { name = "旋花人V5" },
    { name = "烈焰人" },
    { name = "烈焰人V2" },
    { name = "烈焰人V3" },
    { name = "烈焰人V4" },
    { name = "烈焰人V5" },
    { name = "钻孔人" },
    { name = "钻孔人V2" },
    { name = "钻孔人V3" },
    { name = "钻孔人V4" },
    { name = "钻孔人V5" },
    { name = "金属人" },
    { name = "金属人V2" },
    { name = "金属人V3" },
    { name = "金属人V4" },
    { name = "金属人V5" },
    { name = "庞克" },
    { name = "紫天阳炎" },
    { name = "青龙出洞" },
    { name = "落雷闪" },
    { name = "盖亚刃" },
    { name = "国王人" },
    { name = "国王人V2" },
    { name = "国王人V3" },
    { name = "国王人V4" },
    { name = "国王人V5" },
    { name = "神灯人" },
    { name = "神灯人V2" },
    { name = "神灯人V3" },
    { name = "神灯人V4" },
    { name = "神灯人V5" },
    { name = "保龄人" },
    { name = "保龄人V2" },
    { name = "保龄人V3" },
    { name = "保龄人V4" },
    { name = "保龄人V5" },
    { name = "魔王人" },
    { name = "魔王人V2" },
    { name = "魔王人V3" },
    { name = "魔王人V4" },
    { name = "魔王人V5" },
    { name = "大和人" },
    { name = "大和人V2" },
    { name = "大和人V3" },
    { name = "大和人V4" },
    { name = "大和人V5" },
    { name = "三角斩" },
    { name = "芯片回收" },
    { name = "友助回收" },
    { name = "原型臂∑" },
    { name = "佛鲁迪" },
    { name = "小夜曲" },
    { name = "平衡" },
    { name = "暗黑护环" },
    { name = "原型臂Ω" },
    { name = "佛鲁迪+" },
    { name = "佛鲁迪GS" },
    { name = "Z加农炮1" },
    { name = "Z加农炮2" },
    { name = "Z加农炮3" },
    { name = "Z-气力拳" },
    { name = "Z-力冲拳" },
    { name = "Z-力重拳" },
    { name = "Z-变换剑" },
    { name = "Z溜溜1" },
    { name = "Z溜溜2" },
    { name = "Z溜溜3" },
    { name = "Z-踏前斩" },
    { name = "Z-踏连斩" },
    { name = "计时弹+" },
    { name = "连爆霰弹" },
    { name = "水泡霰弹" },
    { name = "火焰霰弹" },
    { name = "梦幻剑" },
    { name = "元素剑" },
    { name = "斩邪剑" },
    { name = "双重英雄" },
    { name = "巨型鼠弹" },
    { name = "诅咒军团" },
    { name = "水灵军团" },
    { name = "毒法老王" },
    { name = "影子保镖" },
    { name = "护罩500" },
    { name = "神圣支援" },
    { name = "气力投射" },
    { name = "英雄再现" },
    { name = "大地之裁" },
    { name = "战士勇力" },
    { name = "王者形态" },
    { name = "C-Guard" },
    { name = "C-Shield" },
    { name = "C-Reflct" },
    { name = "C-AntiDm" },
    { name = "DlayCube" },
    { name = "DlayWatr" },
    { name = "DlayFlwr" },
    { name = "DlyBustr" },
    { name = "DlayZap" },
    { name = "DlayFire" },
    { name = "DlayAqua" },
    { name = "DlyTwstr" },
    { name = "DlyInvis" },
    { name = "Z-Punch" },
    { name = "Punisher" },
    { name = "Restock" },
    { name = "拉修支援" },
    { name = "比特支援" },
    { name = "探戈支援" },
    { name = "????" },
    { name = "Plan-B" },
    { name = "Chckmate" },
    { name = "PoisMist" },
    { name = "SoulGang" },
    { name = "Err&Del" },
    { name = "Backup" }
]
navicust_parts = [
    { name = "超级装甲" },
    { name = "子弹穿甲" },
    { name = "蓄气穿甲" },
    { name = "预置草地" },
    { name = "预置冰地" },
    { name = "预置岩浆" },
    { name = "预置沙地" },
    { name = "预置钢板" },
    { name = "预置圣域" },
    { name = "芯片槽+1" },
    { name = "芯片槽+2" },
    { name = "高级+1" },
    { name = "高级+2" },
    { name = "格挡" },
    { name = "护盾" },
    { name = "反射盾" },
    { name = "幻影鞋" },
    { name = "浮游鞋" },
    { name = "替身魔术" },
    { name = "压缩" },
    { name = "能量转换" },
    { name = "侦测原型" },
    { name = "潜行" },
    { name = "油性身体" },
    { name = "我是鱼" },
    { name = "电池模式" },
    { name = "丛林乐园" },
    { name = "芯片猎人" },
    { name = "空气鞋" },
    { name = "紧身衣" },
    { name = "快槽" },
    { name = "拉修支援" },
    { name = "比特支援" },
    { name = "探戈支援" },
    { name = "蓄攻+1" },
    { name = "HP+100" },
    { name = "HP+200" },
    { name = "HP+300" },
    { name = "HP+500" },
    { name = "扩容5" },
    { name = "攻击+1" },
    { name = "连射+1" },
    { name = "蓄速+1" },
    { name = "BUG终止" },
    { name = "幽默感" },
    { name = "穷凶极恶" },
    { name = "火力全开" },
    { name = "究极+1" },
    { name = "彩斗装甲" },
    { name = "黑暗执照" },
]
styles = [
    { name = "普通形态" },
    { name = "普通形态" },
    { name = "电击强攻" },
    { name = "火焰强攻" },
    { name = "水浪强攻" },
    { name = "木叶强攻" },
    { name = "电击重装" },
    { name = "火焰重装" },
    { name = "水浪重装" },
    { name = "木叶重装" },
    { name = "电击友助" },
    { name = "火焰友助" },
    { name = "水浪友助" },
    { name = "木叶友助" },
    { name = "电击护盾" },
    { name = "火焰护盾" },
    { name = "水浪护盾" },
    { name = "木叶护盾" },
    { name = "电击大地" },
    { name = "火焰大地" },
    { name = "水浪大地" },
    { name = "木叶大地" },
    { name = "电击暗影" },
    { name = "火焰暗影" },
    { name = "水浪暗影" },
    { name = "木叶暗影" },
    { name = "电击BUG" },
    { name = "火焰BUG" },
    { name = "水浪BUG" },
    { name = "木叶BUG" },
]
