[patch]
title = "BA流星 红色鬼牌（锁定版） 界面汉化"
authors = [
    "brianuuu <38166666+brianuuu@users.noreply.github.com>",
    "ahackerjack",
]

[versions.'10.0.0']
netplay_compatibility = "bn6_ba_lockon"

[versions.'10.0.0'.rom_overrides]
language = "zh-CN"
chips = [
    { name = "洛克炮" },
    { name = "加农炮" },
    { name = "强化加农炮" },
    { name = "重型加农炮" },
    { name = "等离子枪" },
    { name = "狂烈火神炮1" },
    { name = "狂烈火神炮2" },
    { name = "狂烈火神炮3" },
    { name = "狂烈火神炮X" },
    { name = "空气散弹1" },
    { name = "空气散弹2" },
    { name = "空气散弹3" },
    { name = "战车炮1" },
    { name = "战车炮2" },
    { name = "战车炮3" },
    { name = "姆科技射线1" },
    { name = "姆科技射线2" },
    { name = "姆科技射线3" },
    { name = "破甲定时炸弹" },
    { name = "火焰环" },
    { name = "机械火舌1" },
    { name = "机械火舌2" },
    { name = "机械火舌3" },
    { name = "广域波" },
    { name = "隐形激光1" },
    { name = "隐形激光2" },
    { name = "隐形激光3" },
    { name = "泡沫之星1" },
    { name = "泡沫之星2" },
    { name = "泡沫之星3" },
    { name = "雷电球" },
    { name = "闪电龙头1" },
    { name = "闪电龙头2" },
    { name = "闪电龙头3" },
    { name = "电力脉冲1" },
    { name = "电力脉冲2" },
    { name = "电力脉冲3" },
    { name = "种子喷发1" },
    { name = "种子喷发2" },
    { name = "种子喷发3" },
    { name = "滚动记录1" },
    { name = "滚动记录2" },
    { name = "滚动记录3" },
    { name = "气力机枪1" },
    { name = "气力机枪2" },
    { name = "气力机枪3" },
    { name = "热焰龙" },
    { name = "电力龙" },
    { name = "水龙" },
    { name = "木龙" },
    { name = "气垫球" },
    { name = "钻锥臂" },
    { name = "龙卷风" },
    { name = "噪音风暴" },
    { name = "迷你炸弹" },
    { name = "微型手榴弹" },
    { name = "巨型手榴弹" },
    { name = "闪光炸弹1" },
    { name = "闪光炸弹2" },
    { name = "闪光炸弹3" },
    { name = "嘭嘭炸弹" },
    { name = "水针1" },
    { name = "水针2" },
    { name = "水针3" },
    { name = "玉米射击1" },
    { name = "玉米射击2" },
    { name = "玉米射击3" },
    { name = "BUG炸弹" },
    { name = "青草手榴弹" },
    { name = "冰霜手榴弹" },
    { name = "毒沼手榴弹" },
    { name = "剑" },
    { name = "宽剑" },
    { name = "英雄剑" },
    { name = "宽刃" },
    { name = "长刃" },
    { name = "烈火斩" },
    { name = "碧水斩" },
    { name = "雷电斩" },
    { name = "翠木斩" },
    { name = "狂风侵袭" },
    { name = "双重接近" },
    { name = "接近姆切砍X" },
    { name = "孤胆之剑" },
    { name = "台风之舞" },
    { name = "妖刀村正" },
    { name = "剑斗大师" },
    { name = "元素剑" },
    { name = "破甲佩剑" },
    { name = "导弹射击" },
    { name = "双重射击" },
    { name = "三重射击" },
    { name = "地波冲击1" },
    { name = "地波冲击2" },
    { name = "地波冲击3" },
    { name = "浪客一刀斩1" },
    { name = "浪客一刀斩2" },
    { name = "浪客一刀斩3" },
    { name = "小小热水壶1" },
    { name = "小小热水壶2" },
    { name = "小小热水壶3" },
    { name = "炽焰虫1" },
    { name = "炽焰虫2" },
    { name = "炽焰虫3" },
    { name = "空中突袭1" },
    { name = "空中突袭2" },
    { name = "空中突袭3" },
    { name = "热焰上勾拳1" },
    { name = "热焰上勾拳2" },
    { name = "热焰上勾拳3" },
    { name = "怒焰火球1" },
    { name = "怒焰火球2" },
    { name = "怒焰火球3" },
    { name = "杀手传感器1" },
    { name = "杀手传感器2" },
    { name = "杀手传感器3" },
    { name = "回旋手里剑1" },
    { name = "回旋手里剑2" },
    { name = "回旋手里剑3" },
    { name = "竹枪" },
    { name = "武装重锤1" },
    { name = "武装重锤2" },
    { name = "武装重锤3" },
    { name = "钢铁外壳1" },
    { name = "钢铁外壳2" },
    { name = "钢铁外壳3" },
    { name = "死神镰刀1" },
    { name = "死神镰刀2" },
    { name = "死神镰刀3" },
    { name = "突风" },
    { name = "抽风机" },
    { name = "反射盾1" },
    { name = "反射盾2" },
    { name = "反射盾3" },
    { name = "巨人战斧" },
    { name = "野兽挥击1" },
    { name = "野兽挥击2" },
    { name = "野兽挥击3" },
    { name = "数字球" },
    { name = "灭世流星" },
    { name = "正义的一击" },
    { name = "大型枪弹" },
    { name = "旋转枪" },
    { name = "石头方块" },
    { name = "定时炸弹1" },
    { name = "隐形地雷" },
    { name = "泡沫射击" },
    { name = "黑色墨汁" },
    { name = "混乱射击" },
    { name = "冻结射击" },
    { name = "稻草人" },
    { name = "地藏像" },
    { name = "毒气阿努比斯" },
    { name = "冰战场" },
    { name = "回复10" },
    { name = "回复30" },
    { name = "回复50" },
    { name = "回复80" },
    { name = "回复120" },
    { name = "回复150" },
    { name = "回复200" },
    { name = "回复300" },
    { name = "黑暗流星" },
    { name = "区域侵蚀器" },
    { name = "毒液泛滥" },
    { name = "偷窃复仇" },
    { name = "地面复原" },
    { name = "死斗" },
    { name = "神圣地面" },
    { name = "炸弹臂" },
    { name = "左进之路" },
    { name = "右出之路" },
    { name = "慢速蓄积" },
    { name = "快速蓄积" },
    { name = "量表全满" },
    { name = "子弹强化" },
    { name = "BUG修正" },
    { name = "隐身" },
    { name = "防护罩" },
    { name = "防护罩100" },
    { name = "防护罩200" },
    { name = "灵光" },
    { name = "三重剑" },
    { name = "地狱转轮" },
    { name = "附加麻痹" },
    { name = "反安装" },
    { name = "鼓励背叛" },
    { name = "变身术" },
    { name = "空手夺白刃" },
    { name = "毒苹果" },
    { name = "疾速猛冲2" },
    { name = "黑暗地波" },
    { name = "攻击+10" },
    { name = "飞叶臂" },
    { name = "疾速猛冲3" },
    { name = "攻击+30" },
    { name = "水之臂" },
    { name = "精灵之怒" },
    { name = "疾速猛冲1" },
    { name = "雪球" },
    { name = "定时炸弹2" },
    { name = "定时炸弹3" },
    { name = "大型炸弹" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "萝露" },
    { name = "萝露V2" },
    { name = "萝露V3" },
    { name = "孤胆" },
    { name = "孤胆V2" },
    { name = "孤胆V3" },
    { name = "烈焰金牛" },
    { name = "烈焰金牛V2" },
    { name = "烈焰金牛V3" },
    { name = "电力人" },
    { name = "电力人V2" },
    { name = "电力人V3" },
    { name = "森林豺狼" },
    { name = "森林豺狼V2" },
    { name = "森林豺狼V3" },
    { name = "乌鸦骑士" },
    { name = "乌鸦骑士V2" },
    { name = "乌鸦骑士V3" },
    { name = "冲锋人" },
    { name = "冲锋人V2" },
    { name = "冲锋人V3" },
    { name = "赤红流星射击" },
    { name = "赤红流星射击V2" },
    { name = "赤红流星射击V3" },
    { name = "木叶波" },
    { name = "木叶波V2" },
    { name = "木叶波V3" },
    { name = "拉普拉斯" },
    { name = "拉普拉斯V2" },
    { name = "拉普拉斯V3" },
    { name = "墓葬鬼牌" },
    { name = "墓葬鬼牌V2" },
    { name = "墓葬鬼牌V3" },
    { name = "双重梦幻" },
    { name = "双重梦幻V2" },
    { name = "双重梦幻V3" },
    { name = "飞翼天鹅" },
    { name = "飞翼天鹅V2" },
    { name = "飞翼天鹅V3" },
    { name = "泡沫巨蟹" },
    { name = "泡沫巨蟹V2" },
    { name = "泡沫巨蟹V3" },
    { name = "马戏团人" },
    { name = "马戏团人V2" },
    { name = "马戏团人V3" },
    { name = "音符天琴" },
    { name = "音符天琴V2" },
    { name = "音符天琴V3" },
    { name = "BUG形态" },
    { name = "BUG形态V2" },
    { name = "BUG形态V3" },
    { name = "卡尼尔" },
    { name = "卡尼尔V2" },
    { name = "卡尼尔V3" },
    { name = "血雨" },
    { name = "血雨V2" },
    { name = "血雨V3" },
    { name = "Z之力" },
    { name = "EXE之力" },
    { name = "流星之力" },
    { name = "Z火神炮" },
    { name = "黑暗广域波" },
    { name = "黑暗龙卷风" },
    { name = "火神炮臂" },
    { name = "黑暗钻头" },
    { name = "暗之剑" },
    { name = "黑暗雷电" },
    { name = "战士血脉" },
    { name = "黑暗环绕" },
    { name = "黑暗加农炮" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "佛鲁迪" },
    { name = "二重身魔镜" },
    { name = "孤胆破空斩" },
    { name = "跨界合作" },
    { name = "库雷卡吐息" },
    { name = "佛鲁迪另" },
    { name = "毁灭导弹" },
    { name = "十字分割" },
    { name = "姆之屏障" },
    { name = "法尔沙龙卷风" },
    { name = "终极变换" },
    { name = "蛇发女妖魔眼" },
    { name = "苦痛狱火" },
    { name = "" },
    { name = "蝙蝠加农炮1" },
    { name = "蝙蝠加农炮2" },
    { name = "蝙蝠加农炮3" },
    { name = "蝙蝠加农炮4" },
    { name = "野兽出笼" },
    { name = "震撼加农炮1" },
    { name = "震撼加农炮2" },
    { name = "震撼加农炮3" },
    { name = "广域燃烧1" },
    { name = "广域燃烧2" },
    { name = "广域燃烧3" },
    { name = "烈焰勾拳1" },
    { name = "烈焰勾拳2" },
    { name = "烈焰勾拳3" },
    { name = "强力波浪1" },
    { name = "强力波浪2" },
    { name = "强力波浪3" },
    { name = "玉米派对" },
    { name = "平行外壳" },
    { name = "破坏脉冲" },
    { name = "破甲定时炸弹GA" },
    { name = "墓葬鬼牌GA" },
    { name = "超级广域" },
    { name = "超级爆破" },
    { name = "梦之剑" },
    { name = "伟哉火焰环" },
    { name = "地狱气垫球" },
    { name = "二重身魔镜" },
    { name = "贴身护卫" },
    { name = "双人英雄" },
    { name = "黑暗救世主" },
    { name = "统御噪声" },
    { name = "太阳与月" },
    { name = "双生领袖" },
    { name = "无限力量" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "????" },
    { name = "斗士剑" },
    { name = "音速爆击" },
    { name = "诅咒" },
    { name = "神罚" },
    { name = "十字剑" },
    { name = "超级音速" },
    { name = "双重梦幻" },
    { name = "莱西支援" },
    { name = "比特支援" },
    { name = "探戈支援" },
    { name = "冰块" },
    { name = "Z光剑" },
    { name = "白色胶囊" },
    { name = "紫色胶囊" },
    { name = "粉红胶囊" },
    { name = "治愈球" },
    { name = "磁铁地面" },
    { name = "最后一枪" },
    { name = "数字陷阱" },
    { name = "" },
    { name = "野兽出笼" },
    { name = "野兽出笼" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "高热压缩" },
    { name = "D电力剑" },
    { name = "R切砍" },
    { name = "K死亡光线" },
    { name = "喷发冲锋" },
    { name = "水柱花洒" },
    { name = "E印第安战斧" },
    { name = "F龙卷风" },
    { name = "RC破坏者" },
    { name = "尘埃破碎" },
    { name = "接近斩" },
]
navicust_parts = [
    { name = "无" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "超级装甲" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "改装1" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "改装2" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "MEGA文件1" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "MEGA文件2" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "GIGA文件1" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "初始防护罩" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "盾" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "反射" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "替身" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "漂浮鞋" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "飞行鞋" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "紧身衣" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "随机切换" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "号码开启" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "流星洛克人" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "战斧" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "水" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "利爪" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "天狗" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "磁铁" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "百万富翁" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "幽默感" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "节奏诗歌" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "滑步跑者" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "自我回复" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "孤胆噪声" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "自动锁定" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "环形探测" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "侧方探测" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "BUG停止器" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "莱西支援" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "比特支援" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "探戈支援" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "攻击+1" },
    { name = "攻击+1" },
    { name = "攻击+1" },
    { name = "攻击+1" },
    { name = "连射+1" },
    { name = "连射+1" },
    { name = "连射+1" },
    { name = "连射+1" },
    { name = "充能+1" },
    { name = "充能+1" },
    { name = "充能+1" },
    { name = "充能+1" },
    { name = "攻击MAX" },
    { name = "攻击MAX" },
    { name = "攻击MAX" },
    { name = "攻击MAX" },
    { name = "连射MAX" },
    { name = "连射MAX" },
    { name = "连射MAX" },
    { name = "连射MAX" },
    { name = "充能MAX" },
    { name = "充能MAX" },
    { name = "充能MAX" },
    { name = "充能MAX" },
    { name = "HP+50" },
    { name = "HP+50" },
    { name = "HP+50" },
    { name = "HP+50" },
    { name = "HP+100" },
    { name = "HP+100" },
    { name = "HP+100" },
    { name = "HP+100" },
    { name = "HP+200" },
    { name = "HP+200" },
    { name = "HP+200" },
    { name = "HP+200" },
    { name = "HP+300" },
    { name = "HP+300" },
    { name = "HP+300" },
    { name = "HP+300" },
    { name = "HP+400" },
    { name = "HP+400" },
    { name = "HP+400" },
    { name = "HP+400" },
    { name = "HP+500" },
    { name = "HP+500" },
    { name = "HP+500" },
    { name = "HP+500" },
]
