[patch]
title = "洛克人EXE2 界面汉化"
authors = ["Capcom"]

[versions.'1.0.0']
netplay_compatibility = "exe2_interface"

[versions.'1.0.0'.rom_overrides]
language = "zh-CN"
chips = [
    { name = "   " },
    { name = "加农炮" },
    { name = "高超加农炮" },
    { name = "MEGA加农炮" },
    { name = "散弹枪" },
    { name = "V字枪" },
    { name = "十字枪" },
    { name = "散射枪" },
    { name = "泡沫散弹" },
    { name = "泡沫V字" },
    { name = "泡沫十字" },
    { name = "泡沫散射" },
    { name = "热焰散弹" },
    { name = "热焰V字" },
    { name = "热焰十字" },
    { name = "热焰散射" },
    { name = "迷你炸弹" },
    { name = "小型炸弹" },
    { name = "十字炸弹" },
    { name = "大型炸弹" },
    { name = "丛林炸弹1" },
    { name = "丛林炸弹2" },
    { name = "丛林炸弹3" },
    { name = "剑" },
    { name = "宽剑" },
    { name = "长剑" },
    { name = "烈焰剑" },
    { name = "水斩剑" },
    { name = "电力剑" },
    { name = "烈焰刃" },
    { name = "水刃" },
    { name = "电力刃" },
    { name = "接近斩" },
    { name = "村正" },
    { name = "改装剑" },
    { name = "两手苦无1" },
    { name = "两手苦无2" },
    { name = "两手苦无3" },
    { name = "居合架式" },
    { name = "冲击波" },
    { name = "音速波" },
    { name = "动能波" },
    { name = "地震动1" },
    { name = "地震动2" },
    { name = "地震动3" },
    { name = "气力拳" },
    { name = "寒冰拳" },
    { name = "攻击+20" },
    { name = "攻击+30" },
    { name = "领航员+40" },
    { name = "冲刺攻击" },
    { name = "铁球" },
    { name = "炮丸" },
    { name = "双重针" },
    { name = "三重针" },
    { name = "四重针" },
    { name = "三叉戟" },
    { name = "巨鼠1" },
    { name = "巨鼠2" },
    { name = "巨鼠3" },
    { name = "巨鼠烟火" },
    { name = "龙卷风" },
    { name = "秋风落叶" },
    { name = "热风" },
    { name = "烈焰冲击" },
    { name = "兔环1" },
    { name = "兔环2" },
    { name = "兔环3" },
    { name = "毒香料1" },
    { name = "毒香料2" },
    { name = "毒香料3" },
    { name = "卫星1" },
    { name = "卫星2" },
    { name = "卫星3" },
    { name = "溜溜球1" },
    { name = "溜溜球2" },
    { name = "溜溜球3" },
    { name = "磁铁炸弹1" },
    { name = "磁铁炸弹2" },
    { name = "磁铁炸弹3" },
    { name = "流星9" },
    { name = "流星12" },
    { name = "流星15" },
    { name = "流星18" },
    { name = "破碎锤" },
    { name = "诅咒盾1" },
    { name = "诅咒盾2" },
    { name = "诅咒盾3" },
    { name = "定时炸弹1" },
    { name = "定时炸弹2" },
    { name = "定时炸弹3" },
    { name = "云" },
    { name = "多云" },
    { name = "密云" },
    { name = "隐形地雷" },
    { name = "前方侦测" },
    { name = "双向侦测" },
    { name = "遥控雷鼓1" },
    { name = "遥控雷鼓2" },
    { name = "遥控雷鼓3" },
    { name = "水液气球" },
    { name = "电力气球" },
    { name = "热焰气球" },
    { name = "间歇泉" },
    { name = "岩浆龙" },
    { name = "神石" },
    { name = "老树" },
    { name = "毒气面具" },
    { name = "毒气脸" },
    { name = "漩涡" },
    { name = "黑洞漩涡" },
    { name = "钢盔防御" },
    { name = "防护罩" },
    { name = "击碎地面1" },
    { name = "击碎地面3" },
    { name = "全线击出" },
    { name = "竹枪" },
    { name = "宙斯之锤" },
    { name = "青铜铁拳" },
    { name = "白银铁拳" },
    { name = "黄金铁拳" },
    { name = "变化剑" },
    { name = "回复10" },
    { name = "回复30" },
    { name = "回复50" },
    { name = "回复80" },
    { name = "回复120" },
    { name = "回复150" },
    { name = "回复200" },
    { name = "回复300" },
    { name = "地面窃取" },
    { name = "区域窃取" },
    { name = "偷窃惩罚" },
    { name = "死斗1" },
    { name = "死斗2" },
    { name = "死斗3" },
    { name = "抓取机器" },
    { name = "他人意志" },
    { name = "逃脱" },
    { name = "飞行鞋" },
    { name = "地面复原" },
    { name = "远距蜡烛1" },
    { name = "远距蜡烛2" },
    { name = "远距蜡烛3" },
    { name = "石头方块" },
    { name = "三棱镜" },
    { name = "地藏像" },
    { name = "突风" },
    { name = "抽风机" },
    { name = "毒气阿努比斯" },
    { name = "缓慢量表" },
    { name = "快速量表" },
    { name = "量表全满" },
    { name = "隐身1" },
    { name = "隐身2" },
    { name = "隐身3" },
    { name = "天井中" },
    { name = "地底下" },
    { name = "石头躯体" },
    { name = "影分身1" },
    { name = "影分身2" },
    { name = "影分身3" },
    { name = "紧身衣" },
    { name = "泡沫包覆" },
    { name = "树叶盾" },
    { name = "水之灵" },
    { name = "焰之灵" },
    { name = "木之灵" },
    { name = "电之灵" },
    { name = "梦之灵1" },
    { name = "梦之灵2" },
    { name = "梦之灵3" },
    { name = "磁力线" },
    { name = "岩浆线" },
    { name = "冰线" },
    { name = "草原线" },
    { name = "岩浆战场" },
    { name = "冰战场" },
    { name = "草原战场" },
    { name = "神圣地面" },
    { name = "嫉妒" },
    { name = "火气严禁" },
    { name = "避雷针" },
    { name = "大洪水" },
    { name = "替身" },
    { name = "空手夺白刃" },
    { name = "领航员征用" },
    { name = "劣质药品" },
    { name = "攻击+10" },
    { name = "火+40" },
    { name = "水+40" },
    { name = "木+40" },
    { name = "电+40" },
    { name = "领航员+20" },
    { name = "萝露" },
    { name = "萝露V2" },
    { name = "萝露V3" },
    { name = "气力人" },
    { name = "气力人V2" },
    { name = "气力人V3" },
    { name = "布鲁斯" },
    { name = "布鲁斯V2" },
    { name = "布鲁斯V3" },
    { name = "空气人" },
    { name = "空气人V2" },
    { name = "空气人V3" },
    { name = "快速人" },
    { name = "快速人V2" },
    { name = "快速人V3" },
    { name = "剪刀人" },
    { name = "剪刀人V2" },
    { name = "剪刀人V3" },
    { name = "阴影人" },
    { name = "阴影人V2" },
    { name = "阴影人V3" },
    { name = "骑士人" },
    { name = "骑士人V2" },
    { name = "骑士人V3" },
    { name = "磁铁人" },
    { name = "磁铁人V2" },
    { name = "磁铁人V3" },
    { name = "结冻人" },
    { name = "结冻人V2" },
    { name = "结冻人V3" },
    { name = "高热人" },
    { name = "高热人V2" },
    { name = "高热人V3" },
    { name = "青蛙人" },
    { name = "青蛙人V2" },
    { name = "青蛙人V3" },
    { name = "闪电人" },
    { name = "闪电人V2" },
    { name = "闪电人V3" },
    { name = "蛇人" },
    { name = "蛇人V2" },
    { name = "蛇人V3" },
    { name = "闸门人" },
    { name = "闸门人V2" },
    { name = "闸门人V3" },
    { name = "行星人" },
    { name = "行星人V2" },
    { name = "行星人V3" },
    { name = "烧夷弹人" },
    { name = "烧夷弹人V2" },
    { name = "烧夷弹人V3" },
    { name = "法老王人" },
    { name = "法老王人V2" },
    { name = "法老王人V3" },
    { name = "佛鲁迪" },
    { name = "佛鲁迪V2" },
    { name = "佛鲁迪V3" },
    { name = "大红海啸" },
    { name = "结冻炸弹" },
    { name = "蓄电火花" },
    { name = "盖亚剑" },
    { name = "黑色炸弹" },
    { name = "斗士剑" },
    { name = "骑士剑" },
    { name = "英雄剑" },
    { name = "流星群" },
    { name = "骚灵" },
    { name = "火戈斯巴鲁" },
    { name = "水戈斯巴鲁" },
    { name = "电戈斯巴鲁" },
    { name = "木戈斯巴鲁" },
    { name = "闸门人SP" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "圣殿" },
    { name = "" },
    { name = "赛塔加农炮1" },
    { name = "赛塔加农炮2" },
    { name = "赛塔加农炮3" },
    { name = "超级爆破" },
    { name = "赛塔炮丸" },
    { name = "赛塔巨鼠1" },
    { name = "赛塔巨鼠2" },
    { name = "赛塔巨鼠3" },
    { name = "奥米加加农炮1" },
    { name = "奥米加加农炮2" },
    { name = "奥米加加农炮3" },
    { name = "MEGA死亡爆裂" },
    { name = "奥米加炮丸" },
    { name = "奥米加巨鼠1" },
    { name = "奥米加巨鼠2" },
    { name = "奥米加巨鼠3" },
    { name = "川流箭" },
    { name = "极大炸弹" },
    { name = "梦之剑1" },
    { name = "梦之剑2" },
    { name = "梦之剑3" },
    { name = "机枪拳" },
    { name = "愤怒诅咒" },
    { name = "GIGA定时炸弹" },
    { name = "沉重践踏" },
    { name = "毒气法老王" },
    { name = "闸门魔术" },
    { name = "气力射击" },
    { name = "巨大爱心" },
    { name = "贴身护卫" },
    { name = "双人英雄" },
    { name = "黑暗救世主" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "神罚" },
    { name = "法老王陷阱" },
    { name = "双重行星" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "遥控闸门" },
    { name = "" },
    { name = "？？？？" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
]

