[patch]
title = "BBBN3 界面汉化"
authors = ["ssbmars <46971717+ssbmars@users.noreply.github.com>"]
source = "https://github.com/ssbmars/BBN3"

[versions.'0.0.5']
netplay_compatibility = "bbn3_3"

[versions.'0.0.5'.rom_overrides]
language = "zh-CN"
chips = [
    { name = "洛克炮" },
    { name = "加农炮" },
    { name = "高超加农炮" },
    { name = "MEGA加农炮" },
    { name = "空气弹1" },
    { name = "空气弹2" },
    { name = "空气弹3" },
    { name = "岩浆加农炮1" },
    { name = "岩浆加农炮2" },
    { name = "岩浆加农炮3" },
    { name = "散弹枪" },
    { name = "V字枪" },
    { name = "侧击枪" },
    { name = "散射枪" },
    { name = "泡沫散弹" },
    { name = "泡沫V字" },
    { name = "泡沫侧击" },
    { name = "热焰散弹" },
    { name = "热焰V字" },
    { name = "热焰侧击" },
    { name = "迷你炸弹" },
    { name = "单炸弹" },
    { name = "双炸弹" },
    { name = "三炸弹" },
    { name = "炮丸" },
    { name = "冰冻炮丸" },
    { name = "熔岩炮丸" },
    { name = "黑色炸弹1" },
    { name = "黑色炸弹2" },
    { name = "黑色炸弹3" },
    { name = "剑" },
    { name = "宽剑" },
    { name = "长剑" },
    { name = "烈焰剑" },
    { name = "水斩剑" },
    { name = "电力剑" },
    { name = "竹剑" },
    { name = "改装剑" },
    { name = "变化剑" },
    { name = "接近斩" },
    { name = "接近十字斩" },
    { name = "恐慌情绪" },
    { name = "风压剑" },
    { name = "居合架式" },
    { name = "冲击波" },
    { name = "音速波" },
    { name = "动能波" },
    { name = "气力拳" },
    { name = "气力直拳" },
    { name = "气力冲击" },
    { name = "空气风暴1" },
    { name = "空气风暴2" },
    { name = "空气风暴3" },
    { name = "冲刺攻击" },
    { name = "烈焰冲击" },
    { name = "图腾1" },
    { name = "图腾2" },
    { name = "图腾3" },
    { name = "巨鼠1" },
    { name = "巨鼠2" },
    { name = "巨鼠3" },
    { name = "海哨" },
    { name = "红海哨" },
    { name = "泥海哨" },
    { name = "破碎锤" },
    { name = "龙卷风" },
    { name = "兔环1" },
    { name = "兔环2" },
    { name = "兔环3" },
    { name = "溜溜球1" },
    { name = "溜溜球2" },
    { name = "溜溜球3" },
    { name = "毒香料1" },
    { name = "毒香料2" },
    { name = "毒香料3" },
    { name = "竹枪" },
    { name = "梦幻位" },
    { name = "鼹地鼠" },
    { name = "绿色绳索1" },
    { name = "绿色绳索2" },
    { name = "绿色绳索3" },
    { name = "大型枪弹1" },
    { name = "大型枪弹2" },
    { name = "大型枪弹3" },
    { name = "回力镖1" },
    { name = "回力镖2" },
    { name = "回力镖3" },
    { name = "随机流星" },
    { name = "全局流星" },
    { name = "射击流星" },
    { name = "冰冻波1" },
    { name = "冰冻波2" },
    { name = "冰冻波3" },
    { name = "电浆球1" },
    { name = "电浆球2" },
    { name = "电浆球3" },
    { name = "蜂箭1" },
    { name = "蜂箭2" },
    { name = "蜂箭3" },
    { name = "定时炸弹" },
    { name = "隐形地雷" },
    { name = "杀手传感器1" },
    { name = "杀手传感器2" },
    { name = "杀手传感器3" },
    { name = "诅咒盾1" },
    { name = "诅咒盾2" },
    { name = "诅咒盾3" },
    { name = "间歇泉" },
    { name = "毒气面具" },
    { name = "毒气脸" },
    { name = "重摇1" },
    { name = "重摇2" },
    { name = "重摇3" },
    { name = "巨大波" },
    { name = "火山加农炮" },
    { name = "冲刺鹰" },
    { name = "燃烧十字" },
    { name = "巨鼠烟火" },
    { name = "钢盔防御" },
    { name = "击碎地面1" },
    { name = "击碎地面3" },
    { name = "回复10" },
    { name = "回复30" },
    { name = "回复50" },
    { name = "回复80" },
    { name = "回复120" },
    { name = "回复150" },
    { name = "回复200" },
    { name = "回复300" },
    { name = "地面窃取" },
    { name = "区域窃取" },
    { name = "招来蛇" },
    { name = "手足之情1" },
    { name = "偷窃凝胶1" },
    { name = "偷窃凝胶2" },
    { name = "偷窃凝胶3" },
    { name = "偷窃惩罚" },
    { name = "偷窃复仇" },
    { name = "死斗1" },
    { name = "死斗2" },
    { name = "死斗3" },
    { name = "石头方块" },
    { name = "三棱镜" },
    { name = "突风" },
    { name = "抽风机" },
    { name = "石头手臂1" },
    { name = "石头手臂2" },
    { name = "石头手臂3" },
    { name = "NO光线1" },
    { name = "NO光线2" },
    { name = "NO光线3" },
    { name = "士兵" },
    { name = "骑士" },
    { name = "城堡" },
    { name = "针刺机器1" },
    { name = "针刺机器2" },
    { name = "针刺机器3" },
    { name = "缓慢量表" },
    { name = "快速量表" },
    { name = "地面复原" },
    { name = "隐身" },
    { name = "黑暗洞" },
    { name = "地下鼹鼠1" },
    { name = "地下鼹鼠2" },
    { name = "地下鼹鼠3" },
    { name = "影分身" },
    { name = "小矮兵" },
    { name = "线圈兔" },
    { name = "飞行鞋" },
    { name = "手足之情2" },
    { name = "加油歌" },
    { name = "噪音" },
    { name = "定音鼓" },
    { name = "防护罩" },
    { name = "100防护罩" },
    { name = "200防护罩" },
    { name = "灵光" },
    { name = "超级北风" },
    { name = "神圣地面" },
    { name = "岩浆战场" },
    { name = "冰战场" },
    { name = "草原战场" },
    { name = "沙战场" },
    { name = "金属战场" },
    { name = "圣殿" },
    { name = "剑兵" },
    { name = "吠狼" },
    { name = "茶蘑菇" },
    { name = "水母" },
    { name = "杀手之眼" },
    { name = "领航员征用" },
    { name = "替身" },
    { name = "空手夺白刃" },
    { name = "劣质药品" },
    { name = "复制损伤" },
    { name = "攻击+10" },
    { name = "火+30" },
    { name = "水+30" },
    { name = "电+30" },
    { name = "木+30" },
    { name = "领航员+20" },
    { name = "梦之灵" },
    { name = "妖刀村正" },
    { name = "地藏像" },
    { name = "毒气阿努比斯" },
    { name = "攻击+30" },
    { name = "领航员+40" },
    { name = "英雄剑" },
    { name = "宙斯之锤" },
    { name = "神石" },
    { name = "老树" },
    { name = "量表全满" },
    { name = "流星群" },
    { name = "骚灵" },
    { name = "嫉妒" },
    { name = "红炎" },
    { name = "地下水脉" },
    { name = "雷电" },
    { name = "盖亚剑" },
    { name = "萝露" },
    { name = "萝露V2" },
    { name = "萝露V3" },
    { name = "气力人" },
    { name = "气力人V2" },
    { name = "气力人V3" },
    { name = "气力人V4" },
    { name = "气力人V5" },
    { name = "布鲁斯" },
    { name = "布鲁斯V2" },
    { name = "布鲁斯V3" },
    { name = "布鲁斯V4" },
    { name = "布鲁斯V5" },
    { name = "闪光人" },
    { name = "闪光人V2" },
    { name = "闪光人V3" },
    { name = "闪光人V4" },
    { name = "闪光人V5" },
    { name = "野兽人" },
    { name = "野兽人V2" },
    { name = "野兽人V3" },
    { name = "野兽人V4" },
    { name = "野兽人V5" },
    { name = "泡沫人" },
    { name = "泡沫人V2" },
    { name = "泡沫人V3" },
    { name = "泡沫人V4" },
    { name = "泡沫人V5" },
    { name = "沙漠人" },
    { name = "沙漠人V2" },
    { name = "沙漠人V3" },
    { name = "沙漠人V4" },
    { name = "沙漠人V5" },
    { name = "植物人" },
    { name = "植物人V2" },
    { name = "植物人V3" },
    { name = "植物人V4" },
    { name = "植物人V5" },
    { name = "烈焰人" },
    { name = "烈焰人V2" },
    { name = "烈焰人V3" },
    { name = "烈焰人V4" },
    { name = "烈焰人V5" },
    { name = "钻头人" },
    { name = "钻头人V2" },
    { name = "钻头人V3" },
    { name = "钻头人V4" },
    { name = "钻头人V5" },
    { name = "金属人" },
    { name = "金属人V2" },
    { name = "金属人V3" },
    { name = "金属人V4" },
    { name = "金属人V5" },
    { name = "庞克" },
    { name = "火蜥蜴" },
    { name = "大喷水" },
    { name = "闪电霹雳" },
    { name = "盖亚刃" },
    { name = "国王人" },
    { name = "国王人V2" },
    { name = "国王人V3" },
    { name = "国王人V4" },
    { name = "国王人V5" },
    { name = "烟雾人" },
    { name = "烟雾人V2" },
    { name = "烟雾人V3" },
    { name = "烟雾人V4" },
    { name = "烟雾人V5" },
    { name = "保龄球人" },
    { name = "保龄球人V2" },
    { name = "保龄球人V3" },
    { name = "保龄球人V4" },
    { name = "保龄球人V5" },
    { name = "黑暗人" },
    { name = "黑暗人V2" },
    { name = "黑暗人V3" },
    { name = "黑暗人V4" },
    { name = "黑暗人V5" },
    { name = "大和人" },
    { name = "大和人V2" },
    { name = "大和人V3" },
    { name = "大和人V4" },
    { name = "大和人V5" },
    { name = "三角刀锋" },
    { name = "文件夹复原" },
    { name = "领航员回收" },
    { name = "原型之臂∑" },
    { name = "佛鲁迪" },
    { name = "赛雷纳德" },
    { name = "两成败" },
    { name = "黑暗灵光" },
    { name = "原型之臂Ω" },
    { name = "佛鲁迪另" },
    { name = "佛鲁迪GS" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "赛塔加农炮1" },
    { name = "赛塔加农炮2" },
    { name = "赛塔加农炮3" },
    { name = "赛塔拳" },
    { name = "赛塔直拳" },
    { name = "赛塔冲击" },
    { name = "赛塔变化" },
    { name = "赛塔溜溜球1" },
    { name = "赛塔溜溜球2" },
    { name = "赛塔溜溜球3" },
    { name = "赛塔接近1" },
    { name = "赛塔接近2" },
    { name = "GIGA定时炸弹" },
    { name = "超级爆破" },
    { name = "泡沫散射" },
    { name = "热焰散射" },
    { name = "梦之剑" },
    { name = "元素剑" },
    { name = "恶裂斩" },
    { name = "双人英雄" },
    { name = "高超巨鼠" },
    { name = "无尽诅咒" },
    { name = "落雨凝胶" },
    { name = "毒气法老王" },
    { name = "贴身护卫" },
    { name = "500防护罩" },
    { name = "巨大爱心" },
    { name = "气力射击" },
    { name = "双人央雄" },
    { name = "母体震荡" },
    { name = "胜者之力" },
    { name = "大师型态" },
    { name = "C防御" },
    { name = "C盾" },
    { name = "C反射" },
    { name = "C替身" },
    { name = "集气方块" },
    { name = "集气水铁炮" },
    { name = "集气花" },
    { name = "集气子弹" },
    { name = "集气兔环" },
    { name = "集气火焰放射器" },
    { name = "集气泡沫散弹" },
    { name = "集气秋风落叶" },
    { name = "集气隐身" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "赛塔拳" },
    { name = "" },
    { name = "" },
    { name = "" },
    { name = "神罚" },
    { name = "设备补充" },
    { name = "莱西支援" },
    { name = "比特支援" },
    { name = "探戈支援" },
    { name = "？？？？" },
    { name = "作战变更" },
    { name = "将死" },
    { name = "烟雾毒气" },
    { name = "灵魂双身" },
    { name = "错误&删除" },
    { name = "足轻增援" },
]
navicust_parts = [
    { name = "NONE" },
    { name = "NONE" },
    { name = "NONE" },
    { name = "NONE" },
    { name = "超级装甲" },
    { name = "超级装甲" },
    { name = "超级装甲" },
    { name = "超级装甲" },
    { name = "破碎飞弹" },
    { name = "破碎飞弹" },
    { name = "破碎飞弹" },
    { name = "破碎飞弹" },
    { name = "破碎集气" },
    { name = "破碎集气" },
    { name = "破碎集气" },
    { name = "破碎集气" },
    { name = "设置绿" },
    { name = "设置绿" },
    { name = "设置绿" },
    { name = "设置绿" },
    { name = "设置冰" },
    { name = "设置冰" },
    { name = "设置冰" },
    { name = "设置冰" },
    { name = "设置岩浆" },
    { name = "设置岩浆" },
    { name = "设置岩浆" },
    { name = "设置岩浆" },
    { name = "设置沙" },
    { name = "设置沙" },
    { name = "设置沙" },
    { name = "设置沙" },
    { name = "设置金属" },
    { name = "设置金属" },
    { name = "设置金属" },
    { name = "设置金属" },
    { name = "设置神圣" },
    { name = "设置神圣" },
    { name = "设置神圣" },
    { name = "设置神圣" },
    { name = "改装1" },
    { name = "改装1" },
    { name = "改装1" },
    { name = "改装1" },
    { name = "改装2" },
    { name = "改装2" },
    { name = "改装2" },
    { name = "改装2" },
    { name = "MEGA文件1" },
    { name = "MEGA文件1" },
    { name = "MEGA文件1" },
    { name = "MEGA文件1" },
    { name = "MEGA文件2" },
    { name = "MEGA文件2" },
    { name = "MEGA文件2" },
    { name = "MEGA文件2" },
    { name = "格挡" },
    { name = "格挡" },
    { name = "格挡" },
    { name = "格挡" },
    { name = "盾" },
    { name = "盾" },
    { name = "盾" },
    { name = "盾" },
    { name = "反射" },
    { name = "反射" },
    { name = "反射" },
    { name = "反射" },
    { name = "影子鞋" },
    { name = "影子鞋" },
    { name = "影子鞋" },
    { name = "影子鞋" },
    { name = "漂浮鞋" },
    { name = "漂浮鞋" },
    { name = "漂浮鞋" },
    { name = "漂浮鞋" },
    { name = "替身魔术" },
    { name = "替身魔术" },
    { name = "替身魔术" },
    { name = "替身魔术" },
    { name = "压缩程序" },
    { name = "压缩程序" },
    { name = "压缩程序" },
    { name = "能量转换" },
    { name = "能量转换" },
    { name = "能量转换" },
    { name = "能量转换" },
    { name = "能量转换" },
    { name = "原型镜" },
    { name = "原型镜" },
    { name = "原型镜" },
    { name = "原型镜" },
    { name = "忍术冲刺" },
    { name = "忍术冲刺" },
    { name = "忍术冲刺" },
    { name = "忍术冲刺" },
    { name = "油性体质" },
    { name = "油性体质" },
    { name = "油性体质" },
    { name = "油性体质" },
    { name = "我是鱼" },
    { name = "我是鱼" },
    { name = "我是鱼" },
    { name = "我是鱼" },
    { name = "电池模式" },
    { name = "电池模式" },
    { name = "电池模式" },
    { name = "电池模式" },
    { name = "丛林地带" },
    { name = "丛林地带" },
    { name = "丛林地带" },
    { name = "丛林地带" },
    { name = "收藏家之眼" },
    { name = "收藏家之眼" },
    { name = "收藏家之眼" },
    { name = "收藏家之眼" },
    { name = "飞行鞋" },
    { name = "飞行鞋" },
    { name = "飞行鞋" },
    { name = "飞行鞋" },
    { name = "紧身衣" },
    { name = "紧身衣" },
    { name = "紧身衣" },
    { name = "紧身衣" },
    { name = "快速量表" },
    { name = "快速量表" },
    { name = "快速量表" },
    { name = "快速量表" },
    { name = "莱西支援" },
    { name = "莱西支援" },
    { name = "莱西支援" },
    { name = "莱西支援" },
    { name = "比特支援" },
    { name = "比特支援" },
    { name = "比特支援" },
    { name = "比特支援" },
    { name = "探戈支援" },
    { name = "探戈支援" },
    { name = "探戈支援" },
    { name = "探戈支援" },
    { name = "武器等级+1" },
    { name = "武器等级+1" },
    { name = "武器等级+1" },
    { name = "武器等级+1" },
    { name = "HP+100" },
    { name = "HP+100" },
    { name = "HP+100" },
    { name = "HP+100" },
    { name = "HP+200" },
    { name = "HP+200" },
    { name = "HP+200" },
    { name = "HP+200" },
    { name = "HP+300" },
    { name = "HP+300" },
    { name = "HP+300" },
    { name = "HP+300" },
    { name = "HP+500" },
    { name = "HP+500" },
    { name = "HP+500" },
    { name = "HP+500" },
    { name = "常规+5" },
    { name = "常规+5" },
    { name = "常规+5" },
    { name = "常规+5" },
    { name = "攻击+1" },
    { name = "攻击+1" },
    { name = "攻击+1" },
    { name = "攻击+1" },
    { name = "连射+1" },
    { name = "连射+1" },
    { name = "连射+1" },
    { name = "连射+1" },
    { name = "集气+1" },
    { name = "集气+1" },
    { name = "集气+1" },
    { name = "集气+1" },
    { name = "BUG停止器" },
    { name = "BUG停止器" },
    { name = "BUG停止器" },
    { name = "BUG停止器" },
    { name = "幽默感" },
    { name = "幽默感" },
    { name = "幽默感" },
    { name = "幽默感" },
    { name = "黑色心灵" },
    { name = "黑色心灵" },
    { name = "黑色心灵" },
    { name = "黑色心灵" },
    { name = "子弹MAX" },
    { name = "子弹MAX" },
    { name = "子弹MAX" },
    { name = "子弹MAX" },
    { name = "GIGA文件1" },
    { name = "GIGA文件1" },
    { name = "GIGA文件1" },
    { name = "GIGA文件1" },
    { name = "彩斗修正档" },
    { name = "彩斗修正档" },
    { name = "彩斗修正档" },
    { name = "彩斗修正档" },
    { name = "黑暗执照" },
    { name = "黑暗执照" },
    { name = "黑暗执照" },
    { name = "黑暗执照" },
]
