[patch]
title = "BN6 All-Stars + BBN6"
authors = [
    "luckytyphlosion <10688458+luckytyphlosion@users.noreply.github.com>",
    "Prof. 9 <prof9@outlook.com>",
    "ssbmars <46971717+ssbmars@users.noreply.github.com>"
]
source = "https://github.com/luckytyphlosion/bn6-all-stars"
license = "MIT"

[versions.'1.0.0']
netplay_compatibility = "bn6allstars"

[versions.'1.1.0']
netplay_compatibility = "bn6allstars_v1.1.0"
